// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: catalogue/catalogue.proto

package catalogue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildCatalogueResponse_ResponseState int32

const (
	BuildCatalogueResponse_RESPONSE_STATE_UNSPECIFIED BuildCatalogueResponse_ResponseState = 0
	BuildCatalogueResponse_RESPONSE_STATE_SUCCESS     BuildCatalogueResponse_ResponseState = 1
	BuildCatalogueResponse_RESPONSE_STATE_FAILED      BuildCatalogueResponse_ResponseState = 2
)

// Enum value maps for BuildCatalogueResponse_ResponseState.
var (
	BuildCatalogueResponse_ResponseState_name = map[int32]string{
		0: "RESPONSE_STATE_UNSPECIFIED",
		1: "RESPONSE_STATE_SUCCESS",
		2: "RESPONSE_STATE_FAILED",
	}
	BuildCatalogueResponse_ResponseState_value = map[string]int32{
		"RESPONSE_STATE_UNSPECIFIED": 0,
		"RESPONSE_STATE_SUCCESS":     1,
		"RESPONSE_STATE_FAILED":      2,
	}
)

func (x BuildCatalogueResponse_ResponseState) Enum() *BuildCatalogueResponse_ResponseState {
	p := new(BuildCatalogueResponse_ResponseState)
	*p = x
	return p
}

func (x BuildCatalogueResponse_ResponseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildCatalogueResponse_ResponseState) Descriptor() protoreflect.EnumDescriptor {
	return file_catalogue_catalogue_proto_enumTypes[0].Descriptor()
}

func (BuildCatalogueResponse_ResponseState) Type() protoreflect.EnumType {
	return &file_catalogue_catalogue_proto_enumTypes[0]
}

func (x BuildCatalogueResponse_ResponseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildCatalogueResponse_ResponseState.Descriptor instead.
func (BuildCatalogueResponse_ResponseState) EnumDescriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{5, 0}
}

// create a catalogue
type CreateContainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContainerResponse) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

// create a query on a content item
type CreateContentQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentReference string   `protobuf:"bytes,1,opt,name=content_reference,json=contentReference,proto3" json:"content_reference,omitempty"`
	Pattern          string   `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Values           []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *CreateContentQueryRequest) Reset() {
	*x = CreateContentQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContentQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentQueryRequest) ProtoMessage() {}

func (x *CreateContentQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentQueryRequest.ProtoReflect.Descriptor instead.
func (*CreateContentQueryRequest) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContentQueryRequest) GetContentReference() string {
	if x != nil {
		return x.ContentReference
	}
	return ""
}

func (x *CreateContentQueryRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *CreateContentQueryRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateContentQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *CreateContentQueryResponse) Reset() {
	*x = CreateContentQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContentQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentQueryResponse) ProtoMessage() {}

func (x *CreateContentQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentQueryResponse.ProtoReflect.Descriptor instead.
func (*CreateContentQueryResponse) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateContentQueryResponse) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

// catalogue actions
type BuildCatalogueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatalogueReference string `protobuf:"bytes,1,opt,name=catalogue_reference,json=catalogueReference,proto3" json:"catalogue_reference,omitempty"`
}

func (x *BuildCatalogueRequest) Reset() {
	*x = BuildCatalogueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildCatalogueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCatalogueRequest) ProtoMessage() {}

func (x *BuildCatalogueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCatalogueRequest.ProtoReflect.Descriptor instead.
func (*BuildCatalogueRequest) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{4}
}

func (x *BuildCatalogueRequest) GetCatalogueReference() string {
	if x != nil {
		return x.CatalogueReference
	}
	return ""
}

type BuildCatalogueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status BuildCatalogueResponse_ResponseState `protobuf:"varint,1,opt,name=status,proto3,enum=catalogue.v1.BuildCatalogueResponse_ResponseState" json:"status,omitempty"`
}

func (x *BuildCatalogueResponse) Reset() {
	*x = BuildCatalogueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildCatalogueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCatalogueResponse) ProtoMessage() {}

func (x *BuildCatalogueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCatalogueResponse.ProtoReflect.Descriptor instead.
func (*BuildCatalogueResponse) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{5}
}

func (x *BuildCatalogueResponse) GetStatus() BuildCatalogueResponse_ResponseState {
	if x != nil {
		return x.Status
	}
	return BuildCatalogueResponse_RESPONSE_STATE_UNSPECIFIED
}

type ListCataloguesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCataloguesRequest) Reset() {
	*x = ListCataloguesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCataloguesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCataloguesRequest) ProtoMessage() {}

func (x *ListCataloguesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCataloguesRequest.ProtoReflect.Descriptor instead.
func (*ListCataloguesRequest) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{6}
}

type ListCataloguesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Catalogues map[string]string `protobuf:"bytes,1,rep,name=catalogues,proto3" json:"catalogues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListCataloguesResponse) Reset() {
	*x = ListCataloguesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCataloguesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCataloguesResponse) ProtoMessage() {}

func (x *ListCataloguesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCataloguesResponse.ProtoReflect.Descriptor instead.
func (*ListCataloguesResponse) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{7}
}

func (x *ListCataloguesResponse) GetCatalogues() map[string]string {
	if x != nil {
		return x.Catalogues
	}
	return nil
}

type ListContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatalogueReference string `protobuf:"bytes,1,opt,name=catalogue_reference,json=catalogueReference,proto3" json:"catalogue_reference,omitempty"`
}

func (x *ListContentRequest) Reset() {
	*x = ListContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentRequest) ProtoMessage() {}

func (x *ListContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentRequest.ProtoReflect.Descriptor instead.
func (*ListContentRequest) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{8}
}

func (x *ListContentRequest) GetCatalogueReference() string {
	if x != nil {
		return x.CatalogueReference
	}
	return ""
}

type ListContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentReference []string `protobuf:"bytes,1,rep,name=content_reference,json=contentReference,proto3" json:"content_reference,omitempty"`
}

func (x *ListContentResponse) Reset() {
	*x = ListContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalogue_catalogue_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentResponse) ProtoMessage() {}

func (x *ListContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogue_catalogue_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentResponse.ProtoReflect.Descriptor instead.
func (*ListContentResponse) Descriptor() ([]byte, []int) {
	return file_catalogue_catalogue_proto_rawDescGZIP(), []int{9}
}

func (x *ListContentResponse) GetContentReference() []string {
	if x != nil {
		return x.ContentReference
	}
	return nil
}

var File_catalogue_catalogue_proto protoreflect.FileDescriptor

var file_catalogue_catalogue_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2f, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x7a, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x11, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x1a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x48, 0x0a, 0x15, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2f, 0x0a, 0x13, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x5f, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x16, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x66, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45,
	0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45,
	0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x02, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xad, 0x01, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x43,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x45, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x13, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x5f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x22, 0x42, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x32, 0xe9, 0x03, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x24, 0x2e,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x27, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x12, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x43,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5b, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75,
	0x65, 0x73, 0x12, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x0b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x63,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x61, 0x75, 0x6c, 0x6a, 0x61, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalogue_catalogue_proto_rawDescOnce sync.Once
	file_catalogue_catalogue_proto_rawDescData = file_catalogue_catalogue_proto_rawDesc
)

func file_catalogue_catalogue_proto_rawDescGZIP() []byte {
	file_catalogue_catalogue_proto_rawDescOnce.Do(func() {
		file_catalogue_catalogue_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalogue_catalogue_proto_rawDescData)
	})
	return file_catalogue_catalogue_proto_rawDescData
}

var file_catalogue_catalogue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalogue_catalogue_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_catalogue_catalogue_proto_goTypes = []any{
	(BuildCatalogueResponse_ResponseState)(0), // 0: catalogue.v1.BuildCatalogueResponse.ResponseState
	(*CreateContainerRequest)(nil),            // 1: catalogue.v1.CreateContainerRequest
	(*CreateContainerResponse)(nil),           // 2: catalogue.v1.CreateContainerResponse
	(*CreateContentQueryRequest)(nil),         // 3: catalogue.v1.CreateContentQueryRequest
	(*CreateContentQueryResponse)(nil),        // 4: catalogue.v1.CreateContentQueryResponse
	(*BuildCatalogueRequest)(nil),             // 5: catalogue.v1.BuildCatalogueRequest
	(*BuildCatalogueResponse)(nil),            // 6: catalogue.v1.BuildCatalogueResponse
	(*ListCataloguesRequest)(nil),             // 7: catalogue.v1.ListCataloguesRequest
	(*ListCataloguesResponse)(nil),            // 8: catalogue.v1.ListCataloguesResponse
	(*ListContentRequest)(nil),                // 9: catalogue.v1.ListContentRequest
	(*ListContentResponse)(nil),               // 10: catalogue.v1.ListContentResponse
	nil,                                       // 11: catalogue.v1.ListCataloguesResponse.CataloguesEntry
}
var file_catalogue_catalogue_proto_depIdxs = []int32{
	0,  // 0: catalogue.v1.BuildCatalogueResponse.status:type_name -> catalogue.v1.BuildCatalogueResponse.ResponseState
	11, // 1: catalogue.v1.ListCataloguesResponse.catalogues:type_name -> catalogue.v1.ListCataloguesResponse.CataloguesEntry
	1,  // 2: catalogue.v1.CatalogueService.CreateContainer:input_type -> catalogue.v1.CreateContainerRequest
	3,  // 3: catalogue.v1.CatalogueService.CreateContentQuery:input_type -> catalogue.v1.CreateContentQueryRequest
	5,  // 4: catalogue.v1.CatalogueService.BuildCatalogue:input_type -> catalogue.v1.BuildCatalogueRequest
	7,  // 5: catalogue.v1.CatalogueService.ListCatalogues:input_type -> catalogue.v1.ListCataloguesRequest
	9,  // 6: catalogue.v1.CatalogueService.ListContent:input_type -> catalogue.v1.ListContentRequest
	2,  // 7: catalogue.v1.CatalogueService.CreateContainer:output_type -> catalogue.v1.CreateContainerResponse
	4,  // 8: catalogue.v1.CatalogueService.CreateContentQuery:output_type -> catalogue.v1.CreateContentQueryResponse
	6,  // 9: catalogue.v1.CatalogueService.BuildCatalogue:output_type -> catalogue.v1.BuildCatalogueResponse
	8,  // 10: catalogue.v1.CatalogueService.ListCatalogues:output_type -> catalogue.v1.ListCataloguesResponse
	10, // 11: catalogue.v1.CatalogueService.ListContent:output_type -> catalogue.v1.ListContentResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_catalogue_catalogue_proto_init() }
func file_catalogue_catalogue_proto_init() {
	if File_catalogue_catalogue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_catalogue_catalogue_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateContainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateContainerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateContentQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateContentQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BuildCatalogueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BuildCatalogueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListCataloguesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListCataloguesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalogue_catalogue_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalogue_catalogue_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalogue_catalogue_proto_goTypes,
		DependencyIndexes: file_catalogue_catalogue_proto_depIdxs,
		EnumInfos:         file_catalogue_catalogue_proto_enumTypes,
		MessageInfos:      file_catalogue_catalogue_proto_msgTypes,
	}.Build()
	File_catalogue_catalogue_proto = out.File
	file_catalogue_catalogue_proto_rawDesc = nil
	file_catalogue_catalogue_proto_goTypes = nil
	file_catalogue_catalogue_proto_depIdxs = nil
}
